server:
  port: 8001

spring:
  application:
    name: FeignApplication

#feign 使用okhttp
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xrnl,application/xrnl,application/json-request-size
      min-request-size: 2048
    reponse:
      enabled: true

